//
// CountryResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CountryResource: JSONEncodable {
    /** The iso2 of the country */
    public var iso2: String?
    /** The iso3 of the country */
    public var iso3: String?
    /** The name of the country resource */
    public var name: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["iso2"] = self.iso2
        nillableDictionary["iso3"] = self.iso3
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
