//
// BRERuleEngineActionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class BRERuleEngineActionsAPI: APIBase {
    /**
     * enum for parameter filterCategory
     */
    public enum FilterCategory_getBREActions: String { 
        case Achievement = "achievement"
        case Behavior = "behavior"
        case Comment = "comment"
        case Disposition = "disposition"
        case Device = "device"
        case Entitlement = "entitlement"
        case Friends = "friends"
        case Fulfillment = "fulfillment"
        case Gamification = "gamification"
        case Inventory = "inventory"
        case Invoice = "invoice"
        case Media = "media"
        case Scheduler = "scheduler"
        case Store = "store"
        case Subscription = "subscription"
        case User = "user"
        case Wallet = "wallet"
        case Custom = "custom"
        case Challenge = "challenge"
        case Activity = "activity"
        case Campaign = "campaign"
        case Event = "event"
    }

    /**
     Get a list of available actions
     
     - parameter filterCategory: (query) Filter for actions that are within a specific category (optional)
     - parameter filterName: (query) Filter for actions that have names containing the given string (optional)
     - parameter filterTags: (query) Filter for actions that have all of the given tags (comma separated list) (optional)
     - parameter filterSearch: (query) Filter for actions containing the given words somewhere within name, description and tags (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getBREActions(filterCategory filterCategory: FilterCategory_getBREActions? = nil, filterName: String? = nil, filterTags: String? = nil, filterSearch: String? = nil, completion: ((data: [ActionResource]?, error: ErrorType?) -> Void)) {
        getBREActionsWithRequestBuilder(filterCategory: filterCategory, filterName: filterName, filterTags: filterTags, filterSearch: filterSearch).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a list of available actions
     - GET /bre/actions
     - <b>Permissions Needed:</b> BRE_RULE_ENGINE_ACTIONS_USER
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant
     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example=[ {
  "variables" : [ {
    "name" : "name",
    "optional" : false,
    "type" : "type"
  }, {
    "name" : "name",
    "optional" : false,
    "type" : "type"
  } ],
  "name" : "name",
  "description" : "description",
  "category" : "achievement",
  "tags" : [ "tags", "tags" ]
}, {
  "variables" : [ {
    "name" : "name",
    "optional" : false,
    "type" : "type"
  }, {
    "name" : "name",
    "optional" : false,
    "type" : "type"
  } ],
  "name" : "name",
  "description" : "description",
  "category" : "achievement",
  "tags" : [ "tags", "tags" ]
} ]}]
     
     - parameter filterCategory: (query) Filter for actions that are within a specific category (optional)
     - parameter filterName: (query) Filter for actions that have names containing the given string (optional)
     - parameter filterTags: (query) Filter for actions that have all of the given tags (comma separated list) (optional)
     - parameter filterSearch: (query) Filter for actions containing the given words somewhere within name, description and tags (optional)

     - returns: RequestBuilder<[ActionResource]> 
     */
    public class func getBREActionsWithRequestBuilder(filterCategory filterCategory: FilterCategory_getBREActions? = nil, filterName: String? = nil, filterTags: String? = nil, filterSearch: String? = nil) -> RequestBuilder<[ActionResource]> {
        let path = "/bre/actions"
        let URLString = JSAPIAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "filter_category": filterCategory?.rawValue,
            "filter_name": filterName,
            "filter_tags": filterTags,
            "filter_search": filterSearch
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[ActionResource]>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
