//
// PaymentsTransactionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class PaymentsTransactionsAPI: APIBase {
    /**
     Get the details for a single transaction
     
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getTransaction(id id: Int32, completion: ((data: TransactionResource?, error: ErrorType?) -> Void)) {
        getTransactionWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get the details for a single transaction
     - GET /transactions/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - examples: [{contentType=application/json, example={
  "transaction_id" : "aeiou",
  "type_hint" : "aeiou",
  "source" : "digital",
  "type" : "aeiou",
  "currency_code" : "aeiou",
  "is_refunded" : false,
  "response" : "aeiou",
  "invoice_id" : 9,
  "details" : "aeiou",
  "id" : 3,
  "create_date" : 7,
  "value" : 2.7189929266748503,
  "successful" : false
}}]
     
     - parameter id: (path) id 

     - returns: RequestBuilder<TransactionResource> 
     */
    public class func getTransactionWithRequestBuilder(id id: Int32) -> RequestBuilder<TransactionResource> {
        var path = "/transactions/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = JSAPIAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<TransactionResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     List and search transactions
     
     - parameter filterInvoice: (query) Filter for transactions from a specific invoice (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getTransactions(filterInvoice filterInvoice: Int32? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: ((data: PageResourceTransactionResource?, error: ErrorType?) -> Void)) {
        getTransactionsWithRequestBuilder(filterInvoice: filterInvoice, size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List and search transactions
     - GET /transactions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - examples: [{contentType=application/json, example={
  "number" : 4,
  "last" : true,
  "size" : 5,
  "total_elements" : 5,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "aeiou",
    "ascending" : true,
    "direction" : "ASC"
  } ],
  "total_pages" : 6,
  "number_of_elements" : 6,
  "content" : [ {
    "transaction_id" : "aeiou",
    "type_hint" : "aeiou",
    "source" : "digital",
    "type" : "aeiou",
    "currency_code" : "aeiou",
    "is_refunded" : false,
    "response" : "aeiou",
    "invoice_id" : 0,
    "details" : "aeiou",
    "id" : 8,
    "create_date" : 4,
    "value" : 2.5967756507268946,
    "successful" : false
  } ],
  "first" : true
}}]
     
     - parameter filterInvoice: (query) Filter for transactions from a specific invoice (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)

     - returns: RequestBuilder<PageResourceTransactionResource> 
     */
    public class func getTransactionsWithRequestBuilder(filterInvoice filterInvoice: Int32? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceTransactionResource> {
        let path = "/transactions"
        let URLString = JSAPIAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "filter_invoice": filterInvoice?.encodeToJSON(),
            "size": size?.encodeToJSON(),
            "page": page?.encodeToJSON(),
            "order": order
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<PageResourceTransactionResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Refund a payment transaction, in full or in part
     
     - parameter id: (path) The id of the transaction to refund 
     - parameter request: (body) Request containing refund details (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func refundTransaction(id id: Int32, request: RefundRequest? = nil, completion: ((data: RefundResource?, error: ErrorType?) -> Void)) {
        refundTransactionWithRequestBuilder(id: id, request: request).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Refund a payment transaction, in full or in part
     - POST /transactions/{id}/refunds
     - Will not allow for refunding more than the full amount even with multiple partial refunds. Money is refunded to the payment method used to make the original payment. Payment method must support refunds.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - examples: [{contentType=application/json, example={
  "transaction_id" : 9,
  "amount" : 7.316182575593041,
  "refund_transaction_id" : 0
}}]
     
     - parameter id: (path) The id of the transaction to refund 
     - parameter request: (body) Request containing refund details (optional)

     - returns: RequestBuilder<RefundResource> 
     */
    public class func refundTransactionWithRequestBuilder(id id: Int32, request: RefundRequest? = nil) -> RequestBuilder<RefundResource> {
        var path = "/transactions/{id}/refunds"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters = request?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<RefundResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
