//
// BreTriggerResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class BreTriggerResource: JSONEncodable {
    public enum Category: String { 
        case Achievement = "achievement"
        case Behavior = "behavior"
        case Comment = "comment"
        case Disposition = "disposition"
        case Device = "device"
        case Entitlement = "entitlement"
        case Friends = "friends"
        case Fulfillment = "fulfillment"
        case Gamification = "gamification"
        case Inventory = "inventory"
        case Invoice = "invoice"
        case Media = "media"
        case Scheduler = "scheduler"
        case Store = "store"
        case Subscription = "subscription"
        case User = "user"
        case Wallet = "wallet"
        case Custom = "custom"
        case Challenge = "challenge"
        case Activity = "activity"
        case Campaign = "campaign"
        case Event = "event"
    }
    /** The category this trigger belongs to. See endpoints for related asset information. All new triggers are in category &#39;custom&#39; */
    public var category: Category?
    /** The unique name for the event. This serves as the unique identifier. Cannot be changed after creation */
    public var eventName: String?
    /** A list of parameters that will be sent with the event when the trigger is fired. These must be included in the event and match the described types */
    public var parameters: [BreTriggerParameterDefinition]?
    /** Where this trigger came from. System triggers cannot be removed or updated */
    public var systemTrigger: Bool?
    /** A list of tags for filtering */
    public var tags: [String]?
    /** A description of the trigger */
    public var triggerDescription: String?
    /** A human readable name for this trigger */
    public var triggerName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["category"] = self.category?.rawValue
        nillableDictionary["event_name"] = self.eventName
        nillableDictionary["parameters"] = self.parameters?.encodeToJSON()
        nillableDictionary["system_trigger"] = self.systemTrigger
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["trigger_description"] = self.triggerDescription
        nillableDictionary["trigger_name"] = self.triggerName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
