//
// ChallengeEventParticipantResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ChallengeEventParticipantResource: JSONEncodable {
    /** The email address of the user */
    public var email: String?
    /** The full name of the user */
    public var fullname: String?
    /** The user&#39;s score */
    public var score: Int64?
    /** The id of the user */
    public var userId: Int32?
    /** The username of the user */
    public var username: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["email"] = self.email
        nillableDictionary["fullname"] = self.fullname
        nillableDictionary["score"] = self.score?.encodeToJSON()
        nillableDictionary["user_id"] = self.userId?.encodeToJSON()
        nillableDictionary["username"] = self.username
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
