//
// ErrorResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ErrorResource: JSONEncodable {
    /** Extra details about the error, if needed */
    public var details: AnyObject?
    /** The JSON key the message pertains to */
    public var field: AnyObject?
    /** The message explaining the error */
    public var message: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["details"] = self.details
        nillableDictionary["field"] = self.field
        nillableDictionary["message"] = self.message
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
