//
// MessageContentResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MessageContentResource: JSONEncodable {
    /** The content of the email */
    public var email: String?
    /** The content of the mobile app push notification */
    public var push: String?
    /** The content of the sms */
    public var sms: String?
    /** The content of the templated email */
    public var templatedEmail: TemplatedEmail?
    /** The content of the websocket message */
    public var websocket: AnyObject?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["email"] = self.email
        nillableDictionary["push"] = self.push
        nillableDictionary["sms"] = self.sms
        nillableDictionary["templated_email"] = self.templatedEmail?.encodeToJSON()
        nillableDictionary["websocket"] = self.websocket
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
