//
// QuickBuyRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class QuickBuyRequest: JSONEncodable {
    /** SKU of item being purchased */
    public var sku: String?
    /** ID of the user making the purchase. If null, currently logged in user will be used. */
    public var userId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["user_id"] = self.userId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
