//
// StoreSubscriptionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class StoreSubscriptionsAPI: APIBase {
    /**
     Create a subscription template
     
     - parameter subscriptionTemplateResource: (body) The new subscription template (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createSubscriptionTemplateUsingPOST(subscriptionTemplateResource subscriptionTemplateResource: SubscriptionTemplateResource? = nil, completion: ((data: SubscriptionTemplateResource?, error: ErrorType?) -> Void)) {
        createSubscriptionTemplateUsingPOSTWithRequestBuilder(subscriptionTemplateResource: subscriptionTemplateResource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create a subscription template
     - POST /subscriptions/templates
     - Subscription Templates define a type of subscription and the properties they have.
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "plan_template" : {
    "name" : "aeiou",
    "created_date" : 123456789,
    "id" : "aeiou",
    "updated_date" : 123456789,
    "properties" : [ {
      "name" : "aeiou",
      "type" : "aeiou",
      "required" : false
    } ]
  },
  "created_date" : 123456789,
  "id" : "aeiou",
  "updated_date" : 123456789,
  "properties" : [ "" ]
}}]
     
     - parameter subscriptionTemplateResource: (body) The new subscription template (optional)

     - returns: RequestBuilder<SubscriptionTemplateResource> 
     */
    public class func createSubscriptionTemplateUsingPOSTWithRequestBuilder(subscriptionTemplateResource subscriptionTemplateResource: SubscriptionTemplateResource? = nil) -> RequestBuilder<SubscriptionTemplateResource> {
        let path = "/subscriptions/templates"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = subscriptionTemplateResource?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SubscriptionTemplateResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Creates a subscription item and associated plans
     
     - parameter subscriptionResource: (body) The subscription to be created (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createSubscriptionUsingPOST(subscriptionResource subscriptionResource: SubscriptionResource? = nil, completion: ((data: SubscriptionResource?, error: ErrorType?) -> Void)) {
        createSubscriptionUsingPOSTWithRequestBuilder(subscriptionResource: subscriptionResource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Creates a subscription item and associated plans
     - POST /subscriptions
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     - examples: [{contentType=application/json, example={
  "geo_policy_type" : "aeiou",
  "template" : "aeiou",
  "short_description" : "aeiou",
  "geo_country_list" : [ "aeiou" ],
  "store_end" : 123456789,
  "unique_key" : "aeiou",
  "availability" : "aeiou",
  "long_description" : "aeiou",
  "sort" : 123,
  "tags" : [ "aeiou" ],
  "consolidation_day_of_month" : 123,
  "plans" : [ {
    "end_date" : 123456789,
    "initial_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "late_payment_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "billing_cycle_length" : 123,
    "reactivation_sku" : "aeiou",
    "currency_code" : "aeiou",
    "recurring_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "min_cycles" : 123,
    "recurring_sku" : "aeiou",
    "max_bill_attempts" : 123,
    "additional_properties" : {
      "key" : ""
    },
    "id" : "aeiou",
    "locked" : false,
    "start_date" : 123456789,
    "initial_sku" : "aeiou",
    "published" : false,
    "grace_period" : 123,
    "consolidated" : false,
    "first_billing_cycle_unit" : "aeiou",
    "late_payment_sku" : "aeiou",
    "first_billing_cycle_length" : 123,
    "migrate_to_plan" : "aeiou",
    "name" : "aeiou",
    "billing_cycle_unit" : "aeiou",
    "reactivation_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "max_cycles" : 123
  } ],
  "store_start" : 123456789,
  "vendor_id" : 123,
  "name" : "aeiou",
  "additional_properties" : {
    "key" : {
      "type" : "aeiou"
    }
  },
  "created_date" : 123456789,
  "id" : 123,
  "updated_date" : 123456789,
  "category" : "aeiou"
}}]
     
     - parameter subscriptionResource: (body) The subscription to be created (optional)

     - returns: RequestBuilder<SubscriptionResource> 
     */
    public class func createSubscriptionUsingPOSTWithRequestBuilder(subscriptionResource subscriptionResource: SubscriptionResource? = nil) -> RequestBuilder<SubscriptionResource> {
        let path = "/subscriptions"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = subscriptionResource?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SubscriptionResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a subscription plan
     
     - parameter id: (path) The id of the subscription 
     - parameter planId: (path) The id of the plan 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deletePlanUsingDELETE(id id: Int32, planId: String, completion: ((error: ErrorType?) -> Void)) {
        deletePlanUsingDELETEWithRequestBuilder(id: id, planId: planId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a subscription plan
     - DELETE /subscriptions/{id}/plans/{planId}
     - Must not be locked or a migration target
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     
     - parameter id: (path) The id of the subscription 
     - parameter planId: (path) The id of the plan 

     - returns: RequestBuilder<Void> 
     */
    public class func deletePlanUsingDELETEWithRequestBuilder(id id: Int32, planId: String) -> RequestBuilder<Void> {
        var path = "/subscriptions/{id}/plans/{planId}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{plan_id}", withString: "\(planId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a subscription template
     
     - parameter id: (path) The id of the template 
     - parameter cascade: (query) force deleting the template if it&#39;s attached to other objects, cascade &#x3D; detach (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteSubscriptionTemplateUsingDELETE(id id: String, cascade: String? = nil, completion: ((error: ErrorType?) -> Void)) {
        deleteSubscriptionTemplateUsingDELETEWithRequestBuilder(id: id, cascade: cascade).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a subscription template
     - DELETE /subscriptions/templates/{id}
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     
     - parameter id: (path) The id of the template 
     - parameter cascade: (query) force deleting the template if it&#39;s attached to other objects, cascade &#x3D; detach (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func deleteSubscriptionTemplateUsingDELETEWithRequestBuilder(id id: String, cascade: String? = nil) -> RequestBuilder<Void> {
        var path = "/subscriptions/templates/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "cascade": cascade
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get a single subscription template
     
     - parameter id: (path) The id of the template 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSubscriptionTemplateUsingGET(id id: String, completion: ((data: SubscriptionTemplateResource?, error: ErrorType?) -> Void)) {
        getSubscriptionTemplateUsingGETWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a single subscription template
     - GET /subscriptions/templates/{id}
     - Subscription Templates define a type of subscription and the properties they have.
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "plan_template" : {
    "name" : "aeiou",
    "created_date" : 123456789,
    "id" : "aeiou",
    "updated_date" : 123456789,
    "properties" : [ {
      "name" : "aeiou",
      "type" : "aeiou",
      "required" : false
    } ]
  },
  "created_date" : 123456789,
  "id" : "aeiou",
  "updated_date" : 123456789,
  "properties" : [ "" ]
}}]
     
     - parameter id: (path) The id of the template 

     - returns: RequestBuilder<SubscriptionTemplateResource> 
     */
    public class func getSubscriptionTemplateUsingGETWithRequestBuilder(id id: String) -> RequestBuilder<SubscriptionTemplateResource> {
        var path = "/subscriptions/templates/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SubscriptionTemplateResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     List and search subscription templates
     
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSubscriptionTemplatesUsingGET(size size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: ((data: PageResourceSubscriptionTemplateResource?, error: ErrorType?) -> Void)) {
        getSubscriptionTemplatesUsingGETWithRequestBuilder(size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List and search subscription templates
     - GET /subscriptions/templates
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     - examples: [{contentType=application/json, example={
  "number" : 123,
  "last" : true,
  "size" : 123,
  "total_elements" : 123456789,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "aeiou",
    "property" : "aeiou",
    "ascending" : true,
    "direction" : "aeiou"
  } ],
  "total_pages" : 123,
  "number_of_elements" : 123,
  "content" : [ {
    "name" : "aeiou",
    "plan_template" : {
      "name" : "aeiou",
      "created_date" : 123456789,
      "id" : "aeiou",
      "updated_date" : 123456789,
      "properties" : [ {
        "name" : "aeiou",
        "type" : "aeiou",
        "required" : false
      } ]
    },
    "created_date" : 123456789,
    "id" : "aeiou",
    "updated_date" : 123456789,
    "properties" : [ "" ]
  } ],
  "first" : true
}}]
     
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)

     - returns: RequestBuilder<PageResourceSubscriptionTemplateResource> 
     */
    public class func getSubscriptionTemplatesUsingGETWithRequestBuilder(size size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceSubscriptionTemplateResource> {
        let path = "/subscriptions/templates"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "size": size?.encodeToJSON(),
            "page": page?.encodeToJSON(),
            "order": order
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<PageResourceSubscriptionTemplateResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Retrieve a single subscription item and associated plans
     
     - parameter id: (path) The id of the subscription 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSubscriptionUsingGET(id id: Int32, completion: ((data: SubscriptionResource?, error: ErrorType?) -> Void)) {
        getSubscriptionUsingGETWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Retrieve a single subscription item and associated plans
     - GET /subscriptions/{id}
     - examples: [{contentType=application/json, example={
  "geo_policy_type" : "aeiou",
  "template" : "aeiou",
  "short_description" : "aeiou",
  "geo_country_list" : [ "aeiou" ],
  "store_end" : 123456789,
  "unique_key" : "aeiou",
  "availability" : "aeiou",
  "long_description" : "aeiou",
  "sort" : 123,
  "tags" : [ "aeiou" ],
  "consolidation_day_of_month" : 123,
  "plans" : [ {
    "end_date" : 123456789,
    "initial_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "late_payment_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "billing_cycle_length" : 123,
    "reactivation_sku" : "aeiou",
    "currency_code" : "aeiou",
    "recurring_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "min_cycles" : 123,
    "recurring_sku" : "aeiou",
    "max_bill_attempts" : 123,
    "additional_properties" : {
      "key" : ""
    },
    "id" : "aeiou",
    "locked" : false,
    "start_date" : 123456789,
    "initial_sku" : "aeiou",
    "published" : false,
    "grace_period" : 123,
    "consolidated" : false,
    "first_billing_cycle_unit" : "aeiou",
    "late_payment_sku" : "aeiou",
    "first_billing_cycle_length" : 123,
    "migrate_to_plan" : "aeiou",
    "name" : "aeiou",
    "billing_cycle_unit" : "aeiou",
    "reactivation_fee" : 1.3579000000000001069366817318950779736042022705078125,
    "max_cycles" : 123
  } ],
  "store_start" : 123456789,
  "vendor_id" : 123,
  "name" : "aeiou",
  "additional_properties" : {
    "key" : {
      "type" : "aeiou"
    }
  },
  "created_date" : 123456789,
  "id" : 123,
  "updated_date" : 123456789,
  "category" : "aeiou"
}}]
     
     - parameter id: (path) The id of the subscription 

     - returns: RequestBuilder<SubscriptionResource> 
     */
    public class func getSubscriptionUsingGETWithRequestBuilder(id id: Int32) -> RequestBuilder<SubscriptionResource> {
        var path = "/subscriptions/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SubscriptionResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     List available subscription items and associated plans
     
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listSubscriptionsUsingGET(size size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: ((data: PageResourceSubscriptionResource?, error: ErrorType?) -> Void)) {
        listSubscriptionsUsingGETWithRequestBuilder(size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List available subscription items and associated plans
     - GET /subscriptions
     - examples: [{contentType=application/json, example={
  "number" : 123,
  "last" : true,
  "size" : 123,
  "total_elements" : 123456789,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "aeiou",
    "property" : "aeiou",
    "ascending" : true,
    "direction" : "aeiou"
  } ],
  "total_pages" : 123,
  "number_of_elements" : 123,
  "content" : [ {
    "geo_policy_type" : "aeiou",
    "template" : "aeiou",
    "short_description" : "aeiou",
    "geo_country_list" : [ "aeiou" ],
    "store_end" : 123456789,
    "unique_key" : "aeiou",
    "availability" : "aeiou",
    "long_description" : "aeiou",
    "sort" : 123,
    "tags" : [ "aeiou" ],
    "consolidation_day_of_month" : 123,
    "plans" : [ {
      "end_date" : 123456789,
      "initial_fee" : 1.3579000000000001069366817318950779736042022705078125,
      "late_payment_fee" : 1.3579000000000001069366817318950779736042022705078125,
      "billing_cycle_length" : 123,
      "reactivation_sku" : "aeiou",
      "currency_code" : "aeiou",
      "recurring_fee" : 1.3579000000000001069366817318950779736042022705078125,
      "min_cycles" : 123,
      "recurring_sku" : "aeiou",
      "max_bill_attempts" : 123,
      "additional_properties" : {
        "key" : ""
      },
      "id" : "aeiou",
      "locked" : false,
      "start_date" : 123456789,
      "initial_sku" : "aeiou",
      "published" : false,
      "grace_period" : 123,
      "consolidated" : false,
      "first_billing_cycle_unit" : "aeiou",
      "late_payment_sku" : "aeiou",
      "first_billing_cycle_length" : 123,
      "migrate_to_plan" : "aeiou",
      "name" : "aeiou",
      "billing_cycle_unit" : "aeiou",
      "reactivation_fee" : 1.3579000000000001069366817318950779736042022705078125,
      "max_cycles" : 123
    } ],
    "store_start" : 123456789,
    "vendor_id" : 123,
    "name" : "aeiou",
    "additional_properties" : {
      "key" : {
        "type" : "aeiou"
      }
    },
    "created_date" : 123456789,
    "id" : 123,
    "updated_date" : 123456789,
    "category" : "aeiou"
  } ],
  "first" : true
}}]
     
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)

     - returns: RequestBuilder<PageResourceSubscriptionResource> 
     */
    public class func listSubscriptionsUsingGETWithRequestBuilder(size size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceSubscriptionResource> {
        let path = "/subscriptions"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "size": size?.encodeToJSON(),
            "page": page?.encodeToJSON(),
            "order": order
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<PageResourceSubscriptionResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Processes subscriptions and charge dues
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func processUsingPOST(completion: ((error: ErrorType?) -> Void)) {
        processUsingPOSTWithRequestBuilder().execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Processes subscriptions and charge dues
     - POST /subscriptions/process
     - OAuth:
       - type: oauth2
       - name: knetik_oauth

     - returns: RequestBuilder<Void> 
     */
    public class func processUsingPOSTWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/subscriptions/process"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Update a subscription template
     
     - parameter id: (path) The id of the template 
     - parameter subscriptionTemplateResource: (body) The subscription template resource object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateSubscriptionTemplateUsingPUT(id id: String, subscriptionTemplateResource: SubscriptionTemplateResource? = nil, completion: ((error: ErrorType?) -> Void)) {
        updateSubscriptionTemplateUsingPUTWithRequestBuilder(id: id, subscriptionTemplateResource: subscriptionTemplateResource).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Update a subscription template
     - PUT /subscriptions/templates/{id}
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     
     - parameter id: (path) The id of the template 
     - parameter subscriptionTemplateResource: (body) The subscription template resource object (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func updateSubscriptionTemplateUsingPUTWithRequestBuilder(id id: String, subscriptionTemplateResource: SubscriptionTemplateResource? = nil) -> RequestBuilder<Void> {
        var path = "/subscriptions/templates/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = subscriptionTemplateResource?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Updates a subscription item and associated plans
     
     - parameter id: (path) The id of the subscription 
     - parameter subscriptionResource: (body) The subscription resource object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateSubscriptionUsingPUT(id id: Int32, subscriptionResource: SubscriptionResource? = nil, completion: ((error: ErrorType?) -> Void)) {
        updateSubscriptionUsingPUTWithRequestBuilder(id: id, subscriptionResource: subscriptionResource).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Updates a subscription item and associated plans
     - PUT /subscriptions/{id}
     - Will not remove plans left out
     - OAuth:
       - type: oauth2
       - name: knetik_oauth
     
     - parameter id: (path) The id of the subscription 
     - parameter subscriptionResource: (body) The subscription resource object (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func updateSubscriptionUsingPUTWithRequestBuilder(id id: Int32, subscriptionResource: SubscriptionResource? = nil) -> RequestBuilder<Void> {
        var path = "/subscriptions/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = subscriptionResource?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
