//
// UtilSecurityAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class UtilSecurityAPI: APIBase {
    /**
     Returns the authentication log for a user
     
     - parameter userId: (query) The user id (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getUserLocationLogUsingGET(userId userId: Int32? = nil, completion: ((data: PageLocationLogResource?, error: ErrorType?) -> Void)) {
        getUserLocationLogUsingGETWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Returns the authentication log for a user
     - GET /security/country-log
     - A log entry is recorded everytime a user requests a new token. Standard pagination available
     - examples: [{output=none}]
     
     - parameter userId: (query) The user id (optional)

     - returns: RequestBuilder<PageLocationLogResource> 
     */
    public class func getUserLocationLogUsingGETWithRequestBuilder(userId userId: Int32? = nil) -> RequestBuilder<PageLocationLogResource> {
        let path = "/security/country-log"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "user_id": userId?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<PageLocationLogResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Returns the authentication token details. Use /users endpoint for detailed user's info
     
     - parameter authentication: (body) The Authentication Object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func userUsingGET(authentication authentication: Authentication? = nil, completion: ((data: TokenDetailsResource?, error: ErrorType?) -> Void)) {
        userUsingGETWithRequestBuilder(authentication: authentication).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Returns the authentication token details. Use /users endpoint for detailed user's info
     - GET /me
     - examples: [{output=none}]
     
     - parameter authentication: (body) The Authentication Object (optional)

     - returns: RequestBuilder<TokenDetailsResource> 
     */
    public class func userUsingGETWithRequestBuilder(authentication authentication: Authentication? = nil) -> RequestBuilder<TokenDetailsResource> {
        let path = "/me"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = authentication?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<TokenDetailsResource>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
